openapi: "3.0.3"
info:
  title: "Сервис обработчик сообщения"
  description: "Notification_project API"
  version: "1.0.0"
servers:
  - url: "https://localhost:8765"
paths:
  /messages:
    post:
      summary: "Отправить сообщение"
      operationId: "addToKafka"
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageRequest"
        required: true
      responses:
        "200":
          description: "OK"
components:
  schemas:
    MessageRequest:
      type: "object"
      properties:
        userName:
          type: "string"
        article:
          type: "string"
        message:
          type: "string"