server:
  port: 0

spring:
  application:
    name: message-sender-service
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      mailing: mailingTopic
    consumer:
      group-id: mailing
      enable-auto-commit: false

  cassandra:
    port: 9042
    contact-points: usersContactsKeyspace
    keyspace-name: usersContactsKeyspace

io:
  reflectoring:
    kafka:
      bootstrap-servers: localhost:9092

# для того, чтобы каждая сущность имела уникальный id
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}


mailing:
  send: true # для того, чтобы можно было неотправлять сообщения (тестирования)
  retrying-count: 3 #  количество попыток заново отправить сообщение после неудачной попытки


