openapi: "3.0.3"
info:
  title: "Сервис работы с контактами пользователей"
  description: "Notification_project API"
  version: "1.0.0"
servers:
  - url: "https://localhost:8765"
paths:
  /contacts:
    post:
      summary: "Загрузить файл с контактами"
      operationId: "save"
      parameters:
        - name: "file"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "binary"
        
      responses:
        "200":
          description: "OK"
    get:
      summary: "Получить загруженный список контактов"
      operationId: "getContacts"
      
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ContactResponse"
    delete:
      summary: "Удалить контакты по имени"
      operationId: "deleteContacts"
      
      requestBody:
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/DeleteRequest"
        required: true
      responses:
        "200":
          description: "OK"
    patch:
      summary: "Изменить контакт контактов"
      operationId: "updateContacts"
      
      requestBody:
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/ContactRequest"
        required: true
      responses:
        "200":
          description: "OK"
components:
  schemas:
    ContactResponse:
      type: "object"
      properties:
        userName:
          type: "string"
        contact:
          type: "string"
        type:
          type: "string"
          enum:
            - "Email"
            - "Tg"
            - "Sms"
            - "Unknown"
    DeleteRequest:
      type: "object"
      properties:
        name:
          type: "string"
    ContactRequest:
      type: "object"
      properties:
        userName:
          type: "string"
        contact:
          type: "string"